---

name: Releases

on:
  # Triggers the workflow on push or pull request events
  # but only for the calamari (default) branch.
  pull_request:
    branches: [manta-pc]
  push:
    branches: [manta-pc]

jobs:
  pre-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    # that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # - name: Set-Up
      #   run: sudo apt install -y
      #        cmake pkg-config libssl-dev
      #        git build-essential clang
      #        libclang-dev curl

      # - name: Install Rustup
      #   run: |
      #     curl https://sh.rustup.rs -sSf | sh -s -- -y
      #     source ~/.cargo/env
      #     rustup update stable
      #     rustup update nightly
      #     rustup target add wasm32-unknown-unknown --toolchain nightly
      #     rustup component add clippy
      #     rustup component add rustfmt

      # - name: Calamari Build
      #   run: |
      #     cargo check --features calamari

      - name: Calamari Build
        run: |
          mkdir -p target/release
          mkdir -p target/release/wbuild/calamari-runtime
          touch target/release/calamari-pc
          touch target/release/wbuild/calamari-runtime/calamari_runtime.compact.wasm

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            types.json
            target/release/calamari-pc
            target/release/wbuild/calamari-runtime/calamari_runtime.compact.wasm